version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_PORT_NUMBER: ${DB_PORT}
    volumes:
      - mariadb_data:/bitnami/mariadb
    ports:
      - '${DB_PORT}:${DB_PORT}'

volumes:
  mariadb_data:
    driver: local